In [1]:
import numpy as np

nombres = np.arange(1, 10)
nombres


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
import itertools
from tqdm import tqdm

for permutation in tqdm(itertools.permutations(nombres, 9)):
    x1, x2, x3, y1, y2, y3, z1, z2, z3 = permutation
    if x1 == 8 and x2 == 1:
        X = np.array([[x1, x2, x3], [y1, y2, y3], [z1, z2, z3]])
        somme_ligne = X.sum(axis=1)
        somme_colonne = X.sum(axis=0)
        somme_diagonale = X.diagonal().sum()
        if len(set(somme_ligne)) == 1 and len(set(somme_colonne)) == 1 and somme_ligne[0] == somme_diagonale:
            print(X)
            break


285303it [00:00, 2624906.26it/s]

[[8 1 6]
 [3 5 7]
 [4 9 2]]


In [18]:
somme_colonne

array([15, 15, 15])

In [19]:
somme_diagonale

np.int64(15)